import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ModalContextProvider, ModalProvider } from "./context/Modal";

const Bhavuka = localFont({
  src: "./fonts/Bhavuka.woff",
  variable: "--font-Bhavuka",
  weight: "100 200 300 400 500",
});

export const metadata: Metadata = {
  title: "Word Puzzle Game",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Bhavuka.className} `}
      >
        <ModalContextProvider>
          {children}
          <div id="modal-root" />
          <ModalProvider />
        </ModalContextProvider>
      </body>
    </html>
  );
}
